name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: metatype1
        uses: fabienthinault/metatype1-github-action@main

      - name: afdko
        uses: fabienhinault/afdko-github-action@main
